### ISSUE TITLE
How to create my own IR_examples

### ISSUE THREAD

**Issue by WillQuCD** [mravanelli/pySpeechRev#1]
Hi
Could you please show me how to create my own IR using ESS technique? 
Or could you share the code?

Thank you in advance!

**Comment by mravanelli** [comment]
Hi, sorry for my late answer. You can fine more detail on the method here https://www.eurasip.org/Proceedings/Eusipco/Eusipco2012/Conference/papers/1569588145.pdf. Consider that to measure IRs with the ESS method you need proper equipments such as a professional loudspeaker....
