### ISSUE TITLE
Missing sample rate for the provided examples

### ISSUE THREAD

**Issue by mbuccoli** [mravanelli/pySpeechRev#2]
Hello Mirco, nice work. I believe it would be better to specify IR's samplerate, and resample it (or the input audio) accordingly before filtering to have meaningful results.
I am assuming you sampled IRs at 16kHz, am I right?

**Comment by mravanelli** [comment]
Hi Michele,
yes, to have meaningful results the impulse response and the clean signal
must have the same sampling frequency. In the TIMIT example provided in the
repository, both the speech signal and the impulse responses are sampled
with fs=16kHz. I can modify the documentation to clarify this aspect.

thank you!

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mbuccoli** [comment]
Thanks, I believe it is worth to clarify this aspect, because this tool will be very helpful to augment any dataset, even beyond the TIMIT. I'll close the issue, thank you. 
Michele
