### ISSUE TITLE
Any document on IR1, IR2, IR3 ?

### ISSUE THREAD

**Issue by mwang-lifesize** [mravanelli/pySpeechRev#3]
Hi 
what are these IRs under IR_examples? Any document on that? 

thanks

**Comment by mravanelli** [comment]
This impulse responses are computed as described in the reference paper:
[1] M. Ravanelli, P. Svaizer, M. Omologo, "Realistic Multi-Microphone Data Simulation for Distant Speech Recognition", in Proceedings of Interspeech 2016. https://arxiv.org/abs/1711.09470

**Comment by mwang-lifesize** [comment]
Thanks

**Comment by FabianRitter** [comment]
Do you know the T60 of each example you have? I see that it is more or less 0.7 average (quite challenging by the way)

**Comment by mravanelli** [comment]
Dear Fabian,
you are right. Those impulse responses are taken from the DIRHA corpus and
measure as specified into the reference paper. In particular, the impulse
responses are measured in a livingroom with a reverberation time of about
0.7 secs. Yes, it is quite challenging.

Mirco
