### ISSUE TITLE
About IR1_16.mat

### ISSUE THREAD

**Issue by MichelleYang2017** [mravanelli/pySpeechRev#4]
Hello,This code is perfect.I just want to know how do you produce the IR1_16.mat.Is trained from data?Is there any paper I can read?Thank you

**Comment by mravanelli** [comment]
Hi, thank you for the interest in my code.
The provided impulse responses are measured in a real environment using the
methodology reported in the following papers:

[1] M. Ravanelli, P. Svaizer, M. Omologo, "Realistic Multi-Microphone Data
Simulation for Distant Speech Recognition", in Proceedings of Interspeech
2016. https://arxiv.org/abs/1711.09470

[2] M. Ravanelli, M. Omologo, "Contaminated speech training methods for
robust DNN-HMM distant speech recognition", in Proceedings of INTERSPEECH
2015. https://arxiv.org/abs/1710.03538

[3] M. Ravanelli, M. Omologo, "The DIRHA-English corpus and related tasks
for distant-speech recognition in domestic environments", in Proceedings of
ASRU 2015. https://arxiv.org/abs/1710.02560

**Comment by MichelleYang2017** [comment]
Thank you
